### ISSUE TITLE
Failed Call API

### ISSUE THREAD

**Issue by v4rien** [Bachtran301/Captain-Tsubasa#1]

**Comment by Bachtran301** [comment]
Hmm,  do u have a picture?

**Comment by v4rien** [comment]
![Screenshot_860](https://github.com/user-attachments/assets/05206f2d-2e80-43bf-9fa4-0c61eacc1d93)

**Comment by Bachtran301** [comment]
@v4rien try to get the query_id again

**Comment by v4rien** [comment]
Solved !! Thanks, sir
